### ISSUE TITLE
Check panel signature and alerting after v9.5.7 sync

### ISSUE THREAD

**Issue by mrtomeq** [KensoBI/kensobi#1]
Alerting changes might not have been synced correctly. I don't see any data in alerts coming from the feature datasource. I also had to revert signature changes since the backend would not compile. Please make changes in branch [v9.5.7](https://github.com/KensoBI/kensobi/tree/v9.5.7).

**Comment by christomecki** [comment]
Alerting feature should be working. I tested it like this:

![image](https://github.com/KensoBI/kensobi/assets/113407220/428f0412-2605-4657-ac0e-3265727d1328)

![image](https://github.com/KensoBI/kensobi/assets/113407220/4c785a5f-5f03-4e0c-a32a-b7ca8c4a9f4d)

![image](https://github.com/KensoBI/kensobi/assets/113407220/e0e83eae-5358-4b76-9591-a1c84a39dc0a)

**Comment by christomecki** [comment]
In the commit: 6fb6578 I restored signature changes with one update - only "kenso" prefixed plugins are treated as valid.

**Comment by christomecki** [comment]
361c10a
I also changed sorting algorithm of connections that our datasources are first on the connections list.

**Comment by mrtomeq** [comment]
LGTM, dzięki!
